### ISSUE TITLE
Unmet peer dependecy: sinon@5.0.7

### ISSUE THREAD

**Issue by wu-lee** [danawoodman/sinon-express-mock#10]
I gather sinon-express-mock currently lists sinon ^4.1.13 as a peer dependency.

Sinon's current release is now 5.0.7.

Is there a plan to update to, or otherwise allow current Sinon releases? Or do I need to downgrade Sinon to use sinon-express-mock?

Thanks!

**Comment by danawoodman** [comment]
Someone had updated this previously in a PR but I forgot to push the code to NPM. Can you try `v2.0.2` and reopen if it still doesn't work?

**Comment by wu-lee** [comment]
I don't think I can reopen this, but I think it is still unresolved: the `package.json` `peerDependency` is still configured as `^4.1.3`.

**Comment by danawoodman** [comment]
Fixed in `v2.0.4` 👍
