### ISSUE TITLE
Unmet peer dependency sinon@5.0.7 (revisited)

### ISSUE THREAD

**Issue by wu-lee** [danawoodman/sinon-express-mock#11]
I don't think I can reopen issue #10 now you've closed it, and perhaps you don't get notifications when I add comments to it.

So, to recapitulate what I said there: I think this issue is still unresolved: `package.json`'s `peerDependencies` is still configured as ^4.1.3.

**Comment by danawoodman** [comment]
I've removed any specific version locking in `v2.0.4`, try again?

**Comment by wu-lee** [comment]
I don't get any complaints about peer dependencies now - thanks.
