### ISSUE TITLE
How do you do POST request mocks?

### ISSUE THREAD

**Issue by kbirger** [danawoodman/sinon-express-mock#15]
I have tried `moqReq({ method: 'POST'})`, but no luck. I don't see anything for it in the code either.

**Comment by danawoodman** [comment]
What are attempting to do? We take anything from the passed in object and return it along with some request method stubs. Also, it is `mockReq` btw 👍

**Comment by danawoodman** [comment]
Please reopen if you think something is broken in the module 👍

**Comment by kbirger** [comment]
Thanks @danawoodman, I do not think this necessarily anything broken with the module, but I don't really know another place to ask, plus, if it turns out to be functionality not supported, there's history for a feature request. You can decide :).

I'm moving from a package named mock-express-request, and I have a piece of middleware I'm testing. The middleware needs to process requests of different types (GET/POST/etc), and its behavior is different based on the type of request. In the other package, I was able to do something like `mockRequest({ method: 'POST'})`, to test my middleware's condition:

```typescript
middleware(req: express.Request, res: express.Response, ...) {
  if (req.method === 'POST') {
    doSomething(); 
  } else { 
    doSomethingElse();
}
```

Can I perform an analogous operation with this package?

Thanks again!

**Comment by danawoodman** [comment]
You should be able to. Have you tried? If you pass `{method: 'POST'}` and then pass the request object to a method, it will be able to operate on it like normal. Give it a shot and let me know!
