### ISSUE TITLE
Unlisted dependencies?

### ISSUE THREAD

**Issue by bakerej** [danawoodman/sinon-express-mock#3]
The example code uses

``
expect(res.json).to.be.calledWith({ foo: request.body.foo.bar })
``

but only imports

``
import route from "../src/foo"
import { mockReq, mockRes } from "sinon-express-mock"
``

Where is "expect" coming from? chai-http has an expect().to.be.calledWith method, but just using it in conjunction with the example code still throws the same error.

**Comment by danawoodman** [comment]
Ah, good catch. I normally make `expect` global in my test helper, but I'll make example use explicit import since it's clearer 👍 

Added in 642c0e7
