### ISSUE TITLE
Example test missing sinon-chai library

### ISSUE THREAD

**Issue by ethanchiddicks** [danawoodman/sinon-express-mock#5]
`expect(res.json).to.be.calledWith({ foo: request.body.foo })` is syntax from the sinon-chai library, and only worked with the following: 
```
const chai = require('chai');
const sinonChai = require('sinon-chai');
const expect = chai.expect;
chai.use(sinonChai);

**Comment by danawoodman** [comment]
@ethanchiddicks would welcome a PR to add that to the docs!
