### ISSUE TITLE
peerDependency warning for sinon@4.1.3

### ISSUE THREAD

**Issue by yjimk** [danawoodman/sinon-express-mock#8]
Hi there!

Pleased to be using your library in our project, however I keep receiving peerDep warnings from npm

```
npm WARN sinon-express-mock@2.0.0 requires a peer of sinon@4.1.3 but none is installed. You must install peer dependencies yourself.
```

We're using sinon@4.5.0 and this library still works a treat. Would it be alright if the peerDep was changed to "^4.1.3" to catch the other minor versions in sinon v4? Submitting a PR for this one now

**Comment by danawoodman** [comment]
Great idea, thanks!
